### ISSUE TITLE
Move indicator parameters to yaml

### ISSUE THREAD

**Issue by karpfen** [mapme-initiative/mapme.pipelines#5]
Currently, most indicator parameters (e.g. `min_size` in `src/gfw.R`) are hard coded in the individual scripts in `src`.
I propose to extend the `config.yml` file to include these parameters.
I'm thinking of something that looks like this in the end:

```yml
default:
  input: ./data/WDPA_WDOECM_Jun2024_Public.parquet
  ncores: 12
  data_path: ./data
  output_path: ./output
  progress: true
  by_region: false
  timeout: 600
  overwrite: false
  wdpa_ver: "latest"
  params:
    resources:
      get_key_biodiversity_areas:
        path: "./kbas.gpkg"
      get_gfw_treecover:
        version: "GFC-2023-v1.11"
    indicators:
      calc_carbon:
        stats: c("min", "mean", "max")
    calc_treecover_area:
      years: 2000:2010
      min_size: 20
      min_cover: 50
```

Does that make sense to you, @goergen95?
